### ISSUE TITLE
what is mysql root password?

### ISSUE THREAD

**Issue by yanliqing** [jinfeijie/lamp#2]
what is mysql root password

**Comment by jinfeijie** [comment]
默认空密码
看`https://github.com/jinfeijie/lamp/blob/master/create_mysql_root.sh`
`https://github.com/jinfeijie/lamp/blob/master/README.md`

**Comment by jinfeijie** [comment]
@yanliqing 默认为空密码
看代码
`https://github.com/jinfeijie/lamp/blob/master/create_mysql_root.sh`
`https://github.com/jinfeijie/lamp/blob/master/README.md`

**Comment by yanliqing** [comment]
@jinfeijie 不好意思，这个意思是需要执行create_mysql_root.sh这个脚本文件么？

**Comment by jinfeijie** [comment]
Docker 自动全部处理完成   看README就可以了   有的参数全在那里面了

**Comment by yanliqing** [comment]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
这是什么原因知道么？

**Comment by jinfeijie** [comment]
@yanliqing 这……  这个是docker版本的，你在docker里面Makefile文件会自动处理的。
拿出来单独运行，似乎不太靠谱。
如果你需要非docker的版本可以访问[lnmp.org](lnmp.org) 获取一键安装包

**Comment by yanliqing** [comment]
我就是向登陆mysql去建个用户，使用mysql -u root这个命令提示上面的错误，似乎是mysql没启动？我看了没有mysql进程id，需要如何启动？

**Comment by jinfeijie** [comment]
@yanliqing 你是docker上部署的嘛？

**Comment by yanliqing** [comment]
嗯

**Comment by jinfeijie** [comment]
@yanliqing [fork ](https://github.com/jinfeijie/lamp/blob/master/Dockerfile#fork-destination-box)本项目，然后修改 `Dockerfile`文件中的第 `47`、`48`行，改成你自己的数据库的账号密码  就ok了。

**Comment by yanliqing** [comment]
@jinfeijie 额，我以为这个镜像已经安装好了mysql和apache了

**Comment by jinfeijie** [comment]
@yanliqing 都是在线同时部署的

**Comment by yanliqing** [comment]
@jinfeijie 有联系方式吗？我想联系你，这边对话有点get不到点

**Comment by jinfeijie** [comment]
@yanliqing [@jinfeijie](https://t.me/jinfeijie)
